### ISSUE TITLE
Decreasing the speed?

### ISSUE THREAD

**Issue by NixTheFae** [darceno/darcenosminecarts#1]
Hi, I hope this isn't an issue asking but I was wondering if it's at all possible to reduce the speed slightly? I absolutely love this datapack as a concept but it almost feels too fast to fully enjoy the environment so I was wondering if there was a way to cut the speed in half.

**Comment by darceno** [comment]
Hey, thanks for reaching out! And no worries; I actually think your opinion is totally valid. I just created a new version with half the speed. You can download it from here or from Modrinth and just replace with the old version :D

**Comment by darceno** [comment]
Hey, thanks for reaching out! And no worries; I actually think your opinion is totally valid. I just created a new version with half the speed. You can download it from here or from Modrinth and just replace it with the old version :D
