### ISSUE TITLE
Update the datapack in 1.21

### ISSUE THREAD

**Issue by SebGrd** [darceno/darcenosminecarts#10]
# Minecraft 1.21 Update
Update the datapack to make it work in 1.21
  
  
**Author's note:**
_I have no clue of how to do it but if you don't want maintain this datapack (or you might not have the time) i may give it a try_ 😉 
_Also you might already be working on it, if that's the case you can close that issue_

**Comment by darceno** [comment]
Updated, and thanks for your willingness!
