### ISSUE TITLE
request version without recipe change

### ISSUE THREAD

**Issue by TimmyWithTheBat21** [darceno/darcenosminecarts#11]
hi i really like your mod would it be possible to disable in a config the recipe changes for the slow version or to make a version without the recipe changes. i personally dont want to "cheat" in survival

**Comment by darceno** [comment]
As I don't think there is much demand for it, I won't publish it on Modrinth, but here it is a version of the mod without the recipe. Just open the zip file and drag the mod to your mod folder:

[darcenos-minecarts-slower-1.4-norecipe.zip](https://github.com/user-attachments/files/16417420/darcenos-minecarts-slower-1.4-norecipe.zip)
