### ISSUE TITLE
Version with just Autonomy 

### ISSUE THREAD

**Issue by axotailyn** [darceno/darcenosminecarts#12]
hello, i really like the autonomy feature of your mod but don't prefer to use the speed boost nor the affordable rails, i could not find any other mod that does just the autonomy for the verison im playing, (Fabric 1.20.1) would it be in the realm of possibility to have a version with just autonomy?

**Comment by darceno** [comment]
Yes, it should be possible. You can try edit it yourself. Download the datapack version, open the zip (or extract it) and delete:

/data/minecraft/**recipe** (the folder)
/data/vanillapluscarts/function/**speed.mcfunction** (the file)

That should probably work.

**Comment by axotailyn** [comment]
thank you for the help, i will look into this
