### ISSUE TITLE
chunk loading doesnt work

### ISSUE THREAD

**Issue by Cramber25** [darceno/darcenosminecarts#15]
Hi, I'm using the mod version of darcenosminecarts and the chunk loading doesnt seem to work no matter if i use chests minecarts or regular minecarts. Futhermore, with this mod installed I can't even manually add chunks via the forceload command since the mod runs forceload remove all every tick. im using version 1.3 for minecraft 1.20.1

**Comment by Cramber25** [comment]
![Screenshot 2024-08-27 at 13 06 41](https://github.com/user-attachments/assets/12ccf795-e5f2-424d-8653-0f713c1dca5f)

**Comment by darceno** [comment]
That's weird. I copied your setup block by block and it works normally on 1.20.1.

![2024-08-27_16 40 38](https://github.com/user-attachments/assets/6323a0ac-9b4a-439a-a592-5920b9bb7c47)

 Are the minecarts faster or that's also is not working? I also noticed you're in a server, is the mod installed on it?

**Comment by Cramber25** [comment]
I downloaded the datapack and it still didn't work, but then I edited the code and fixed it, you can close the issue
