### ISSUE TITLE
(DATAPACK) Minecart kicks me out whenever its on a powered rail and seems to be repeatedly in the hit animation?? (rocking back and forth)

### ISSUE THREAD

**Issue by Voxelizeds** [darceno/darcenosminecarts#16]
tried putting in the datapack for your minecart improvements and it for some reason will not allow me to get back into the minecart and will just boot me off whenever i try to.
![image](https://github.com/user-attachments/assets/821c6b7d-3ebe-4236-94d0-0c3eea9c96ce)

As you are able to see, i'm not in survival and if i were to hit it then it would instantly break. (its slightly slanted i cant get a good picture of it that was like the best i got) As i said in the title it only kicks me out of the cart when it goes onto a powered rail but never when its on a regular rail. I downloaded this datapack because mojang apparently didnt put the datapack for minecart improvements in 1.21.1 (which i currently reside and where i downloaded this datapack for.) i dont know how and why this would happen but it could just be a bug on either my end or ur datapack causing it.

**Comment by darceno** [comment]
You're using activator rails instead of powered Rails. Activator rails eject the player/mob from the minecart when powered.
