### ISSUE TITLE
Both 1.4 Data Packs - Players & Mobs in minecarts suddenly stop after accelerating

### ISSUE THREAD

**Issue by ynnarg** [darceno/darcenosminecarts#18]
### The Issue
When a minecart accelerates via powered rail with either a mob or a player in it, the minecart will abruptly stop, and stay stopped until manually moved either by player controls, or a push.

### Bug Reproduction
To reproduce, place a line of powered rails, and place a minecart onto those rails, then either:
- Try to accelerate the minecart with any mob in it. Or;
- Hop into the minecart as a player, and use movement controls to accelerate the minecart, and then the sudden stop will occur.

(See image below to help reproduce the bug)
![2024-11-06_21 46 55](https://github.com/user-attachments/assets/bd003d48-7f38-4cdf-991e-727ff577b3a6)

Also use these versions to reproduce, versions outside of these have not been tested:
- [DP] Darceno's Minecarts - Slower 1.4 (1.21 - 1.21.1)
- [DP] Darceno's Minecarts 1.4 (1.21 - 1.21.1)

### Useful Info
Environment: Dedicated Host
Version: Paper 1.21.1
Max RAM: 6GB
TPS: 20.0
Connection Quality from Client: 100%

Bukkit Plugins:
- FastAsyncWorldEdit 2.12.0
- WorldGuard 7.0.12 (Disabled)
- Dynmap 3.7
- CoreProtect 22.4 (Disabled)
- EssentialsX 2.20.1 (Disabled)
- ClearLagg 3.2.2 (Disabled)

Spigot Plugins: None

Other Data Packs in World:
- 1024 Block Height 1.21.1

### Console Log
The console did not produce any useful or relevant information. The server was switched from the default data pack to the slower data pack version, in an attempt to get the intended functionality, which resulted in a single warning in the console.

> 06.11 10:53:28 [Server] WARN Missing data pack file/darcenos-minecarts-1.4.zip
> 06.11 10:53:28 [Server] INFO Found new data pack file/darcenos-minecarts-slower-1.4.zip, loading it automatically

**Comment by Cestel2** [comment]
I'm experiencing similar issue. When using minecart it suddenly stops, however when you get out of it, it will continue to ride on it's own.

**Comment by darceno** [comment]
@ynnarg  Thank you for the detailed issue, and sorry for my delayed response.

Unfortunately, this is a problem with Paper that I don't know how (or even if it's possible) to fix. It seems that Paper's optimizations (and probably Spigot etc.) messes with some vanilla mechanics that interfere with certain datapacks.

The datapack works fine on a vanilla, Fabric, or (Neo)Forge server.

@Cestel2 , I assume you're also using a Paper?

**Comment by Cestel2** [comment]
Yeah, kinda. I'm using purpur. I tried to turn off minecart features in the engine config but it didn't seem to do anything.
