### ISSUE TITLE
Doesnt work on paper

### ISSUE THREAD

**Issue by Adamsmashem** [darceno/darcenosminecarts#2]
Using a paper 1.20.4 server with no plugins and this being the only datapack, the minecart will accelerate quickly, then immediately stop, or slow down mostly, making it impossible to move.

Same issue with the slower version, and the one without forceload.

I absolutely love the idea of this datapack, and I think a great application would be on servers, so I hope this can be fixed!

**Comment by darceno** [comment]
Unfortunately, there isn't much I can do. This is not a problem with the datapack but with Paper itself, which is somewhat notorious for its incompatibility with datapacks (especially involving the use of scoreboards, which this datapack relies on). I tried to find some solution for this, but had no luck with it.

Personally, if it's a small server, I would recommend running it with Fabric, especially with Lithium, Ferritecore, and ModernFix installed to help with the performance aspect.

However, if you're really into plugins or need even more performance, also be aware that this datapack works perfectly fine on Spigot servers, so you have that option as well.

I'm sorry for the inconvenience, but I hope you can use this datapack with your friends.
