### ISSUE TITLE
Minecart Chests from mineshafts appear to load chunks as well

### ISSUE THREAD

**Issue by GreatSaltyLake** [darceno/darcenosminecarts#5]
Hi, been digging into an issue on an SMP and after too many hours of troubleshooting, realized what may be happening. As I've been monitoring over time the amount of chest minecarts and chunks actively loaded has been steadily increasing. Currently after a few days there are about 300 chest minecarts in our world with almost none of them being player based. I believe this is causing an increasing amount of chunks to be loaded on our server and has contributed heavy to the memory issues we've been experiencing. Thanks for any insight.

**Comment by peow** [comment]
my suggestion: a version without the chunk loader would be cool

**Comment by darceno** [comment]
@peow There's a [fork](https://github.com/pigupp/vanillaplusminecarts-noload) of the project that does that, if you're interested.

**Comment by darceno** [comment]
Thanks for letting me know, @MichaelJustice10, that was a big oversight on my part. I was struggling to find a solution, but fortunately, @catgirlsky pull request seems to do it. [Version 1.3](https://modrinth.com/datapack/darcenos-minecarts/versions) is out now with the fix. Sorry for any inconvenience.
