### ISSUE TITLE
The mod disables the Vanilla Tweaks Home datapack 

### ISSUE THREAD

**Issue by TheRedPanda7211** [darceno/darcenosminecarts#9]
When I set a home, then attempt to teleport to it, it says the destination has not loaded yet, even though I have set a home
![image](https://github.com/darceno/darcenosminecarts/assets/130399876/6b5ae600-300f-4c2d-98c0-6ed266bc1dcd)

**Comment by darceno** [comment]
I tried to mess around with it but I don't think I'm able to fix it without disabling the chunk load feature, unfortunately.
